// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLe5EW7rRTusCJvDJ61n1iwJSUiYuMO74',
    appId: '1:302732351020:web:373548a4ed29f517c76389',
    messagingSenderId: '302732351020',
    projectId: 'hajjumrahapp-ede59',
    authDomain: 'hajjumrahapp-ede59.firebaseapp.com',
    storageBucket: 'hajjumrahapp-ede59.firebasestorage.app',
    measurementId: 'G-B9V13BBDPW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzNueQzwDOHT6xyj4fAbTAuXxiuV10lZU',
    appId: '1:302732351020:android:a342ce59c91a064ec76389',
    messagingSenderId: '302732351020',
    projectId: 'hajjumrahapp-ede59',
    storageBucket: 'hajjumrahapp-ede59.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvt0Bcd2DdVdhT9qG9E4Ul83VKXLhm8Rc',
    appId: '1:302732351020:ios:e209bb758bcd8b4dc76389',
    messagingSenderId: '302732351020',
    projectId: 'hajjumrahapp-ede59',
    storageBucket: 'hajjumrahapp-ede59.firebasestorage.app',
    iosBundleId: 'com.example.hajjUmrahApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvt0Bcd2DdVdhT9qG9E4Ul83VKXLhm8Rc',
    appId: '1:302732351020:ios:e209bb758bcd8b4dc76389',
    messagingSenderId: '302732351020',
    projectId: 'hajjumrahapp-ede59',
    storageBucket: 'hajjumrahapp-ede59.firebasestorage.app',
    iosBundleId: 'com.example.hajjUmrahApp',
  );
}
